"""initial schema

Revision ID: 0392d8ea3a28
Revises: 
Create Date: 2026-05-17 09:17:14.289388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0392d8ea3a28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=True),
    sa.Column('instagram_access_token', sa.Text(), nullable=True),
    sa.Column('instagram_token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instagram_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instagram_token_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('portal_role', sa.Enum('org', 'brand', 'admin', name='portal_role'), nullable=False),
    sa.Column('status', sa.Enum('pending_org_profile', 'pending_email_verification', 'pending_approval', 'active', 'denied', 'suspended', name='org_user_status'), nullable=False),
    sa.Column('edu_email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edu_email'),
    sa.UniqueConstraint('instagram_user_id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('entity_type', sa.Enum('brand', 'org', name='waitlist_entity_type'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=320), nullable=False),
    sa.Column('intent_message', sa.Text(), nullable=True),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'denied', name='brand_status'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('edu_email', sa.String(length=320), nullable=False),
    sa.Column('instagram_handle', sa.String(length=255), nullable=False),
    sa.Column('tiktok_handle', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('drops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('apply_open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('apply_close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manual_reopen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('brand_tracker_stage', sa.Enum('awaiting_brief', 'in_review', 'approved', 'shipped', 'delivered', 'active', 'finished', name='brand_tracker_stage'), nullable=False),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('total_product_units', sa.Integer(), nullable=True),
    sa.Column('campaign_hashtag', sa.String(length=255), nullable=True),
    sa.Column('applicant_selection_finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'CAROUSEL_ALBUM', name='social_media_type'), nullable=False),
    sa.Column('media_product_type', sa.Enum('FEED', 'REELS', 'STORY', 'AD', name='social_media_product_type'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('profile_activity', sa.Integer(), nullable=True),
    sa.Column('follows', sa.Integer(), nullable=True),
    sa.Column('ig_reels_avg_watch_time', sa.Integer(), nullable=True),
    sa.Column('ig_reels_video_view_total_time', sa.Integer(), nullable=True),
    sa.Column('reels_skip_rate', sa.Float(), nullable=True),
    sa.Column('insights_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_social_posts_platform_external_id')
    )
    op.create_table('drop_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('applied', 'accepted', 'denied', name='application_decision'), nullable=False),
    sa.Column('pitch', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('allocated_units', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drop_tracker_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('awaiting_brief', 'in_review', 'approved', 'shipped', 'delivered', 'active', 'finished', name='brand_tracker_stage'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notify_me',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'drop_id', name='uq_notify_me_org_drop')
    )
    op.create_table('post_campaign_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('org_manual', 'auto_suggested', name='post_link_source'), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['drop_applications.id'], ),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('post_campaign_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('match_reason', sa.Enum('brand_handle_caption', 'campaign_hashtag', 'both', name='suggestion_match_reason'), nullable=False),
    sa.Column('match_evidence', sa.Text(), nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['drop_applications.id'], ),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'application_id', name='uq_post_campaign_suggestions_post_application')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_campaign_suggestions')
    op.drop_table('post_campaign_links')
    op.drop_table('notify_me')
    op.drop_table('drop_tracker_events')
    op.drop_table('drop_applications')
    op.drop_table('social_posts')
    op.drop_table('drops')
    op.drop_table('organizations')
    op.drop_table('email_verification_tokens')
    op.drop_table('brands')
    op.drop_table('waitlist')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate creates PG ENUM types implicitly when the first table that
    # references them is created, but does NOT emit DROP TYPE on table drop.
    # Without these the downgrade leaves dangling types and a subsequent
    # `upgrade head` errors with "type ... already exists". List ordering is
    # irrelevant — none depend on each other.
    bind = op.get_bind()
    for type_name in (
        "portal_role",
        "org_user_status",
        "brand_status",
        "application_decision",
        "brand_tracker_stage",
        "platform",
        "social_media_type",
        "social_media_product_type",
        "post_link_source",
        "suggestion_match_reason",
        "waitlist_entity_type",
    ):
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
