"""add partial unique index for active drop applications

Revision ID: 645b8aa4a5f2
Revises: fcded7900133
Create Date: 2026-06-05 21:13:04.248805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645b8aa4a5f2'
down_revision: Union[str, Sequence[str], None] = 'fcded7900133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_drop_application_active', 'drop_applications', ['drop_id', 'org_id'], unique=True, postgresql_where=sa.text("decision <> 'denied'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_drop_application_active', table_name='drop_applications', postgresql_where=sa.text("decision <> 'denied'"))
    # ### end Alembic commands ###
